// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortlandBusiness.Models;

namespace PortlandBusiness.Migrations
{
    [DbContext(typeof(PortlandBusinessContext))]
    [Migration("20200821211014_Split")]
    partial class Split
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortlandBusiness.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Description = "Downtown Arcade Bar",
                            Name = "Ground Kontrol",
                            Type = "Bar"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Description = "Restaurant and Deli providing fine meats",
                            Name = "Laurelhurst Market",
                            Type = "Steakhouse"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Description = "Korean desserts and coffee drinks",
                            Name = "Soro Soro",
                            Type = "Dessert"
                        },
                        new
                        {
                            RestaurantId = 4,
                            Description = "Delicious local Portland brewery",
                            Name = "Breakside Brewery",
                            Type = "Brewery"
                        },
                        new
                        {
                            RestaurantId = 5,
                            Description = "Best Sushi in town",
                            Name = "Miyamoto Sushi",
                            Type = "Restaurant"
                        });
                });

            modelBuilder.Entity("PortlandBusiness.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            Description = "Large Bookstore",
                            Name = "Powells Books"
                        },
                        new
                        {
                            ShopId = 2,
                            Description = "Crafts and Records",
                            Name = "Tender Loving Empire"
                        },
                        new
                        {
                            ShopId = 3,
                            Description = "Portland's best record store",
                            Name = "Music Millenium"
                        },
                        new
                        {
                            ShopId = 4,
                            Description = "Artsy Comic book shop",
                            Name = "Floating World"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
