// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortlandBusiness.Models;

namespace PortlandBusiness.Migrations
{
    [DbContext(typeof(PortlandBusinessContext))]
    [Migration("20200821203853_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortlandBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Description = "Large Bookstore",
                            Name = "Powells Books",
                            Type = "Retail"
                        },
                        new
                        {
                            BusinessId = 2,
                            Description = "Downtown Arcade Bar",
                            Name = "Ground Kontrol",
                            Type = "Bar"
                        },
                        new
                        {
                            BusinessId = 3,
                            Description = "Restaurant and Deli providing fine meats",
                            Name = "Laurelhurst Market",
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 4,
                            Description = "Korean desserts and coffee drinks",
                            Name = "Soro Soro",
                            Type = "Cafe"
                        },
                        new
                        {
                            BusinessId = 5,
                            Description = "Small live music venue",
                            Name = "Mississippi Studios",
                            Type = "Venue"
                        },
                        new
                        {
                            BusinessId = 6,
                            Description = "Delicious local Portland brewery",
                            Name = "Breakside Brewery",
                            Type = "Brewery"
                        },
                        new
                        {
                            BusinessId = 7,
                            Description = "Best Sushi in town",
                            Name = "Miyamoto Sushi",
                            Type = "Restaurant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
